// flow-typed signature: 2487647abf12c4f66934a4378839a31e
// flow-typed version: <<STUB>>/@ava/babel-preset-stage-4_v^1.0.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@ava/babel-preset-stage-4'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@ava/babel-preset-stage-4' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@ava/babel-preset-stage-4/package-hash' {
  declare module.exports: any;
}

declare module '@ava/babel-preset-stage-4/plugins/best-match' {
  declare module.exports: any;
}

// Filename aliases
declare module '@ava/babel-preset-stage-4/index' {
  declare module.exports: $Exports<'@ava/babel-preset-stage-4'>;
}
declare module '@ava/babel-preset-stage-4/index.js' {
  declare module.exports: $Exports<'@ava/babel-preset-stage-4'>;
}
declare module '@ava/babel-preset-stage-4/package-hash.js' {
  declare module.exports: $Exports<'@ava/babel-preset-stage-4/package-hash'>;
}
declare module '@ava/babel-preset-stage-4/plugins/best-match.js' {
  declare module.exports: $Exports<'@ava/babel-preset-stage-4/plugins/best-match'>;
}
