// flow-typed signature: a055d1691ff1fe5dc007d4cc1fe71fd2
// flow-typed version: <<STUB>>/dom-event-target_v^1.0.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dom-event-target'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dom-event-target' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'dom-event-target/index' {
  declare module.exports: $Exports<'dom-event-target'>;
}
declare module 'dom-event-target/index.js' {
  declare module.exports: $Exports<'dom-event-target'>;
}
